timescale/timescaledb-parallel-copy

README.md
main.go

This will handle files in correct CSV format by default, rather
than have the users discover this option themselves. Also update
README to include a `--copy-options` example.
Fixes #10

Set default CSV options to 'CSV'

---

cmd/timescaledb-parallel-copy/main.go

Add the option to skip the header line, which is quite common in csv files. This cannot be done via `--copy-options`, because these will be applied every time the prepared statement is run.
To test, add a header line to the [csv file](https://timescaledata.blob.core.windows.net/datasets/nyc_data.tar.gz) from the [getting started tutorial](https://docs.timescale.com/v1.2/tutorials/tutorial-hello-nyc).
`vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount`
Observe that importing it without the `--skip-header`, this fails:
`panic: pq: invalid input syntax for type timestamp: "pickup_datetime"`
The …

Add --skip-header flag.

---

cmd/timescaledb-parallel-copy/main.go

There's a variable called `columnCount` in the code that is only written to, but never read. If there was any use for it at some point, the corresponding code must have been removed.
Removing this variable allows us to only split the line only when required by the workaround.
CLA signed.

Remove the columnCount variable and only split line if necessary.

---

cmd/timescaledb-parallel-copy/main.go
go.mod
go.sum

Previously we were re-creating and re-determining the copy command,
delimiters, and other things within the loop of processing each
batch which is unnecessary since it does not change across batches.
This refactor reorganizes that logic and moves the actual batch
processing to a separate function.

Refactor batch processing to be more efficient

---

cmd/timescaledb-parallel-copy/main.go
go.sum

Some users may have large fields for CSVs, which don't work with
the default (64KB). In this PR we provide a flag to specify a larger
size for these cases. Any size less than the default will be ignored
(and a warning printed).
Addresses #25

Allow CSV token size to be specified

---

cmd/timescaledb-parallel-copy/main.go

Fix incorrect warning when token size is equal to default

---

cmd/timescaledb-parallel-copy/main.go

When i was working on some csv file i came across file which had 2 header lines, with this pull request i added an option where you can specify the number of header lines you want to skip.

Added command line option to allow several header lines

---

README.md

Go get is no longer supported
```
go get github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
To install the package outside the module:
```
go install github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy@latest
```

go get no longer supported

---

README.md
cmd/timescaledb-parallel-copy/main.go
internal/batch/scan.go
internal/batch/scan_internal_test.go
internal/batch/scan_test.go

As mentioned in https://github.com/timescale/timescaledb-parallel-copy/commit/8da678ea9800d89e5fa9539819fff92ec0630a99, https://github.com/timescale/timescaledb-parallel-copy/issues/19, and https://github.com/timescale/timescaledb-parallel-copy/issues/50, the batching algorithm assumes that one row consists of exactly one line. If a row contains multi-line quoted column values, and we happen to split that row across multiple batches, we'll fail the `COPY`.
Add a naive CSV parser to Scan() which prevents this accidental splitting. This parser searches the incoming CSV for the `QUOTE` and `ESCAPE` characters (which can be customized by the new `-quote` and `-escape` flags to the tool), and prevents Scan() from sending out a new batch if it detects that we're still inside a quoted value. …

Don't split multi-line rows across batches

---

internal/db/db.go
internal/db/db_internal_test.go

Sets `application_name=timescaledb-parallel-copy` on the Postgres connections.

Set application_name on Postgres connections

---

cmd/timescaledb-parallel-copy/main.go
internal/batch/scan.go
internal/batch/scan_internal_test.go
internal/batch/scan_test.go
internal/db/db.go
internal/db/db_test.go
pkg/csvcopy/csvcopy.go
pkg/csvcopy/csvcopy_test.go

Improve the error handling by actually returning errors from workers instead of panicking. Additionally, Copy now accepts a context that's propagated through the execution and can be cancelled to stop it.

Return error instead of panicking

---

cmd/timescaledb-parallel-copy/main.go
pkg/csvcopy/csvcopy.go

Users familiar with loading CSV data with the COPY command know the 'HEADER' option, and erroneously believe that they should use it with timescaledb-parallel-copy (by passing 'CSV HEADER' to -copy-options).
timescaledb-parallel-copy handles this use-case with the -skip-header option. Passing HEADER to -copy-options results in the first row of every _batch_ being discarded, causing silent data loss.
This change is backwards incompatible, because it aborts on inputs which it previously accepted.
We have not provided a way to pass HEADER to -copy-options, because we don't believe that there is a legitimate use-case for this combination.
Fixes: #59

Abort when 'HEADERS' passed to -copy-options

---

internal/batch/scan.go

If a failure occurs during copy, the worker will return an error and publish it to the errChan. 
in the mean time, the publisher is waiting for a worker to pickup the next batch, but this will never happen as the worker has stopped to process due to the error.
The fix makes sure the publish is protected with the context, this way if the workers signals cancellation, the publisher will skip the write to the channel en return.
Fix #86 
```
$ timescaledb-parallel-copy --batch-size 2000 -columns timestamp,email,product_name,product_price,product_description,address -connection "postgres://tsdbadmin@dg7cvr30ww.xltbtwir0g.dev.metronome-cloud.com:30672/tsdb?sslmode=require" -file bad-250Mb.csv -log-batches --skip-header -workers 1 -table products -verbose
Skipping the first 1 lines of the input. …
```

Fix: write to channel should be protected with context

---

pkg/csvcopy/csvcopy.go
pkg/csvcopy/reporting.go

Added option
```
// WithReportingFunction sets the function that will be called at
// reportingPeriod with information about the copy progress
func WithReportingFunction(f ReportFunc) Option {
return func(c *Copier) {
c.reportingFunction = f
}
}
```
There is a default implementation that maintains default behavior if not specified
The idea is to be able to define your own function to capture the progress when running as a package. We will be using this to report progress over API

Add custom progress report functionality

---

cmd/timescaledb-parallel-copy/main.go
internal/batch/scan.go
internal/batch/scan_test.go
pkg/csvcopy/csvcopy.go
pkg/csvcopy/csvcopy_test.go

I've been trying to import data multiple times just to get an error half way on the process and with no trace of where to look to fix it.
This implementation attempts to capture such errors and generate a meaningful error message.
```
$ timescaledb-parallel-copy --batch-size 2000 -columns timestamp,email,product_name,product_price,product_description,address -connection "postgres://tsdbadmin@dg7cvr30ww.xltbtwir0g.dev.metronome-cloud.com:30672/tsdb?sslmode=require" -file bad-250Mb.csv -log-batches --skip-header -workers 1 -table products -verbose -truncate
Skipping the first 1 lines of the input.
[BATCH] took 567.961244ms, batch size 2000, row rate 3521.367032/sec
[BATCH] took 125.747937ms, batch size 2000, row rate 15904.833492/sec
[BATCH] took 139.151848ms, batch size 2000, row rate …
```

Feat: Report line with error

---

pkg/csvcopy/csvcopy.go

What happens is that on close is not waiting for the goroutine to
finish, which leads to inconsistent progress reports.
This change makes sure the goroutine is part of the wait group

Fix race condition on waiting for progress report to finish

---

pkg/csvcopy/csvcopy.go
pkg/csvcopy/csvcopy_test.go

Dead lock happen because the worker wait group was shared with the support tasks. 
This attempts to separate both processes and make sure all workers finish before the support tasks are stopped

Fix dead-lock on progress report

---

internal/db/db.go

If pgx/v4 and pgx/v5 are registerd. pgx driver will target to the first one that was registered. 
v4 will fail, so we need to force pgx/v5 connection type

Make sure Connect uses pgx/v5

---

pkg/csvcopy/csvcopy.go

If a worker fails, the context is cancelled, this leads to all workers+the scanner stopping immediately.
The race conditions happens because if all the workers close before the scanner, the code will proceed and close the error channel. Then the scanner fails when attempting to publish to the error channel.
This is solved by adding the scanner to the worker group. this will make sure we always wait for all goroutines that publish to errCh to stop

Fix race condition on worker failure

---

pkg/csvcopy/options.go

The option has a boolean flag that was not being used. 
This fixes the problem by making sure the skip is set to 1 when the value is true

Fix WithSkipHeader package option

---

README.md
cmd/timescaledb-parallel-copy/main.go
pkg/csvcopy/csvcopy.go
pkg/csvcopy/csvcopy_test.go
pkg/csvcopy/options.go
pkg/csvcopy/options_test.go
pkg/csvcopy/scan.go
pkg/csvcopy/scan_test.go

The current implementation only supports `--column-names` which requires the user to manually provide the names for the database columns. 
Given that CSV files already support headers, adding `--auto-column-mapping` allows to take advantage of such information and use it to build `--column-names` dynamically. This is less error prone and more flexible. 
The `--column-mapping` flag is added along with `--auto-column-mapping` because it resolves another common problem where your input csv column names do not match the database column names. `--auto-column-mapping` is a concrete case of `--column-mapping` where source and destination are the same name.

feat: column mapping and auto column mapping
